# Generated by Django 4.1.2 on 2022-10-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='likey',
            field=models.IntegerField(default=0),
        ),
    ]
