# Generated by Django 4.1.2 on 2022-10-30 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0002_topic_likey'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='liker',
            field=models.ManyToManyField(blank=True, related_name='liker', to=settings.AUTH_USER_MODEL),
        ),
    ]
