# Generated by Django 4.1.2 on 2022-10-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_topic_liker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='liker',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='likey',
        ),
    ]
